header:
  license:
    spdx-id: Datalayer
    copyright-owner: Datalayer, Inc.
    copyright-year: 2021-2025
    content: |
      Copyright (c) [year] [owner]
      Distributed under the terms of the Modified BSD License.

  paths-ignore:
    - '**/*.ipynb'
    - '**/*.json'
    - '**/*.txt'
    - '**/*.md'
    - '**/*.svg'
    - '**/*.tsbuildinfo'
    - '**/*.yml'
    - '**/*.yaml'
    - '**/build'
    - '**/lib'
    - '**/node_modules'
    - '**/MANIFEST.in'
    - '**/static'
    - '**/typings'
    - '**/schemas'
    - '**/themes'
    - '*.map.js'
    - '*.bundle.js'
    - '**/.*'
    - 'LICENSE'
    - '.devcontainer/resources/'
    - '**/LICENSE.txt'
    - '**/*.nblink'
    - 'docs/docs'
    - 'patches/'

  comment: on-failure