[build-system]
requires = ["hatchling==1.21.1", "jupyterlab==4.1.0b0", "hatch-nodejs-version"]
build-backend = "hatchling.build"

[project]
name = "jupyter_viewer"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "Framework :: Jupyter",
    "Framework :: Jupyter :: JupyterLab",
    "Framework :: Jupyter :: JupyterLab :: 4",
    "Framework :: Jupyter :: JupyterLab :: Extensions",
    "Framework :: Jupyter :: JupyterLab :: Extensions :: Prebuilt",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

dependencies = [
    "jupyter_server>=2,<3"
]
dynamic = ["version", "description", "authors", "urls", "keywords"]

[project.optional-dependencies]
test = [
    "coverage",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-jupyter",
    "pytest-tornasync",
]

[project.scripts]
jupyter-viewer = "jupyter_viewer.serverapplication:main"

[tool.hatch.version]
source = "nodejs"

[tool.hatch.build]
artifacts = [
  "jupyter_viewer/static",
  "jupyter_viewer/templates"
]

[tool.hatch.build.hooks.custom]

[tool.hatch.metadata.hooks.nodejs]
fields = ["description", "authors", "urls"]

[tool.hatch.build.targets.sdist]
artifacts = ["jupyter_viewer/labextension"]
exclude = [".github", "binder", ".yarn"]

[tool.hatch.build.targets.wheel.shared-data]
"jupyter_viewer/labextension" = "share/jupyter/labextensions/@datalayer/jupyter-viewer"
"install.json" = "share/jupyter/labextensions/@datalayer/jupyter-viewer/install.json"
"jupyter-config/server-config" = "etc/jupyter/jupyter_server_config.d"
"jupyter-config/nb-config" = "etc/jupyter/jupyter_notebook_config.d"

[tool.hatch.build.hooks.version]
path = "jupyter_viewer/_version.py"

[tool.hatch.build.hooks.jupyter-builder]
dependencies = ["hatch-jupyter-builder>=0.5"]
build-function = "hatch_jupyter_builder.npm_builder"
ensured-targets = [
    "jupyter_viewer/labextension/static/style.js",
    "jupyter_viewer/labextension/package.json",
]
skip-if-exists = ["jupyter_viewer/labextension/static/style.js"]

[tool.hatch.build.hooks.jupyter-builder.build-kwargs]
build_cmd = "build:prod"
npm = ["jlpm"]

[tool.hatch.build.hooks.jupyter-builder.editable-build-kwargs]
build_cmd = "install:extension"
npm = ["jlpm"]
source_dir = "src"
build_dir = "jupyter_viewer/labextension"

[tool.jupyter-releaser.options]
version_cmd = "hatch version"
